// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class MallGroup
{
    /// <summary>
    /// Group ID
    /// </summary>
    public string Id { get; set; }

    /// <summary>
    /// 分公司名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 分公司代號
    /// </summary>
    public string MallId { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public bool IsUse { get; set; }

    /// <summary>
    /// 資料創建者ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 資料創建時間
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 資料創建來源
    /// </summary>
    public string CreateFrom { get; set; }

    /// <summary>
    /// 最後編輯者ID
    /// </summary>
    public int? Editor { get; set; }

    /// <summary>
    /// 最後編輯時間
    /// </summary>
    public DateTime? EditDate { get; set; }

    /// <summary>
    /// 最後編輯資料來源
    /// </summary>
    public string EditFrom { get; set; }

    public virtual ICollection<RestaurantBranch> RestaurantBranches { get; set; } = new List<RestaurantBranch>();
}