// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class MemberReserve
{
    public long Id { get; set; }

    /// <summary>
    /// 登入會員ID
    /// [FEDSMBR_v3].[Member].[id]
    /// 
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// 餐廳ID
    /// </summary>
    public string CompanyId { get; set; }

    /// <summary>
    /// 餐廳分店ID
    /// </summary>
    public string BranchId { get; set; }

    /// <summary>
    /// 訂位人數
    /// 表示成人訂位人數
    /// </summary>
    public int GroupSize { get; set; }

    /// <summary>
    /// 訂位人數
    /// 代表小孩訂位人數
    /// </summary>
    public int NumberOfKid { get; set; }

    /// <summary>
    /// 聯絡人姓名
    /// </summary>
    public string ContactName { get; set; }

    /// <summary>
    /// 連絡電話
    /// </summary>
    public string ContactPhone { get; set; }

    /// <summary>
    /// 聯絡人性別
    /// 0=男,1=女
    /// </summary>
    public byte ContactGender { get; set; }

    /// <summary>
    /// 聯絡人Email
    /// </summary>
    public string ContactEmail { get; set; }

    /// <summary>
    /// 訂位日期時間
    /// </summary>
    public DateTime Datetime { get; set; }

    /// <summary>
    /// 顧客備註
    /// </summary>
    public string Note { get; set; }

    /// <summary>
    /// 系統備註
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// 資料創建者ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 資料創建時間
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 資料創建來源
    /// </summary>
    public string CreateFrom { get; set; }

    /// <summary>
    /// 最後編輯者ID
    /// </summary>
    public int? Editor { get; set; }

    /// <summary>
    /// 最後編輯時間
    /// </summary>
    public DateTime? EditDate { get; set; }

    /// <summary>
    /// 最後編輯資料來源
    /// </summary>
    public string EditFrom { get; set; }

    public virtual ICollection<MemberReserveLog> MemberReserveLogs { get; set; } = new List<MemberReserveLog>();
}