// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class MemberReserveLog
{
    public long Id { get; set; }

    /// <summary>
    /// 訂位資訊ID
    /// </summary>
    public long ReserveId { get; set; }

    /// <summary>
    /// Log狀態
    /// Create=新增,
    /// Edit=修改,
    /// Delete=刪除
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 修改紀錄
    /// Json陣列
    /// [0]:為修改前資料,
    /// [1]:為修改後資料
    /// </summary>
    public string Json { get; set; }

    /// <summary>
    /// 資料創建者ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 資料創建時間
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 資料創建來源
    /// </summary>
    public string CreateFrom { get; set; }

    public virtual MemberReserve Reserve { get; set; }
}