// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class RestaurantBranch
{
    public string Id { get; set; }

    /// <summary>
    /// 餐廳ID  ([Restaurant].[id])
    /// </summary>
    public string CompanyId { get; set; }

    /// <summary>
    /// 所屬分公司ID  ([MallGroup].[id])
    /// </summary>
    public string GroupId { get; set; }

    /// <summary>
    /// 餐廳分店名稱
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 餐廳地址
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// 聯絡電話
    /// </summary>
    public string PhoneNumber { get; set; }

    /// <summary>
    /// 是否開啟網路訂位
    /// </summary>
    public bool WebBookingEnable { get; set; }

    /// <summary>
    /// 是否開啟預約候位
    /// </summary>
    public bool WebWaitingEnable { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string Remark { get; set; }

    /// <summary>
    /// 資料創建者ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 資料創建時間
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 資料創建來源
    /// </summary>
    public string CreateFrom { get; set; }

    /// <summary>
    /// 最後編輯者ID
    /// </summary>
    public int? Editor { get; set; }

    /// <summary>
    /// 最後編輯時間
    /// </summary>
    public DateTime? EditDate { get; set; }

    /// <summary>
    /// 最後編輯資料來源
    /// </summary>
    public string EditFrom { get; set; }

    public bool? IsUse { get; set; }

    public byte RestaurantCategoryId { get; set; }

    public virtual Restaurant Company { get; set; }

    public virtual MallGroup Group { get; set; }

    public virtual RestaurantCategory RestaurantCategory { get; set; }
}