// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class RestaurantType
{
    public int Id { get; set; }

    /// <summary>
    /// 類型名稱
    /// </summary>
    public string Type { get; set; }

    /// <summary>
    /// 啟用狀態
    /// </summary>
    public byte Status { get; set; }

    /// <summary>
    /// 類型描述
    /// </summary>
    public string Description { get; set; }

    /// <summary>
    /// 資料創建者ID
    /// </summary>
    public int Creator { get; set; }

    /// <summary>
    /// 資料創建時間
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 資料創建來源
    /// </summary>
    public string CreateFrom { get; set; }

    /// <summary>
    /// 最後編輯者ID
    /// </summary>
    public int? Editor { get; set; }

    /// <summary>
    /// 最後編輯時間
    /// </summary>
    public DateTime? EditDate { get; set; }

    /// <summary>
    /// 最後編輯資料來源
    /// </summary>
    public string EditFrom { get; set; }
}