// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Reservation.Models.EFRestaurantModels;

public partial class RestaurantContext : DbContext
{
    public RestaurantContext(DbContextOptions<RestaurantContext> options)
        : base(options)
    {
    }

    public virtual DbSet<MallGroup> MallGroups { get; set; }

    public virtual DbSet<MemberReserve> MemberReserves { get; set; }

    public virtual DbSet<MemberReserveLog> MemberReserveLogs { get; set; }

    public virtual DbSet<MemberWaiting> MemberWaitings { get; set; }

    public virtual DbSet<MemberWaitingLog> MemberWaitingLogs { get; set; }

    public virtual DbSet<Restaurant> Restaurants { get; set; }

    public virtual DbSet<RestaurantBranch> RestaurantBranches { get; set; }

    public virtual DbSet<RestaurantImage> RestaurantImages { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MallGroup>(entity =>
        {
            entity.ToTable("MallGroup");

            entity.Property(e => e.Id)
                .HasMaxLength(60)
                .HasComment("Group ID")
                .HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.EditDate)
                .HasComment("最後編輯時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditFrom)
                .HasMaxLength(20)
                .HasComment("最後編輯資料來源");
            entity.Property(e => e.Editor).HasComment("最後編輯者ID");
            entity.Property(e => e.IsUse).HasComment("啟用狀態");
            entity.Property(e => e.MallId)
                .IsRequired()
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasComment("分公司代號");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50)
                .HasComment("分公司名稱");
        });

        modelBuilder.Entity<MemberReserve>(entity =>
        {
            entity.ToTable("MemberReserve");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.BranchId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("餐廳分店ID");
            entity.Property(e => e.CompanyId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("餐廳ID");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(60)
                .HasComment("聯絡人Email");
            entity.Property(e => e.ContactGender).HasComment("聯絡人性別\r\n0=男,1=女");
            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(30)
                .HasComment("聯絡人姓名");
            entity.Property(e => e.ContactPhone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("連絡電話");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.Datetime)
                .HasComment("訂位日期時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditDate)
                .HasComment("最後編輯時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditFrom)
                .HasMaxLength(20)
                .HasComment("最後編輯資料來源");
            entity.Property(e => e.Editor).HasComment("最後編輯者ID");
            entity.Property(e => e.GroupSize).HasComment("訂位人數\r\n表示成人訂位人數");
            entity.Property(e => e.MemberId)
                .HasComment("登入會員ID\r\n[FEDSMBR_v3].[Member].[id]\r\n")
                .HasColumnName("memberId");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasComment("顧客備註");
            entity.Property(e => e.NumberOfKid).HasComment("訂位人數\r\n代表小孩訂位人數");
            entity.Property(e => e.Remark)
                .HasMaxLength(200)
                .HasComment("系統備註");
        });

        modelBuilder.Entity<MemberReserveLog>(entity =>
        {
            entity.ToTable("MemberReserveLog");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.Json)
                .IsRequired()
                .HasComment("修改紀錄\r\nJson陣列\r\n[0]:為修改前資料,\r\n[1]:為修改後資料");
            entity.Property(e => e.ReserveId).HasComment("訂位資訊ID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("Log狀態\r\nCreate=新增,\r\nEdit=修改,\r\nDelete=刪除");

            entity.HasOne(d => d.Reserve).WithMany(p => p.MemberReserveLogs)
                .HasForeignKey(d => d.ReserveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MemberReserveLog");
        });

        modelBuilder.Entity<MemberWaiting>(entity =>
        {
            entity.ToTable("MemberWaiting");

            entity.Property(e => e.Id)
                .HasMaxLength(60)
                .HasColumnName("id");
            entity.Property(e => e.BranchId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("餐廳分店ID");
            entity.Property(e => e.CompanyId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("餐廳ID");
            entity.Property(e => e.ContactEmail)
                .HasMaxLength(60)
                .HasComment("聯絡人Email");
            entity.Property(e => e.ContactGender).HasComment("聯絡人性別\r\n0=男,1=女");
            entity.Property(e => e.ContactName)
                .IsRequired()
                .HasMaxLength(30)
                .HasComment("聯絡人姓名");
            entity.Property(e => e.ContactPhone)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("連絡電話");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.Datetime)
                .HasComment("訂位日期時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditDate)
                .HasComment("最後編輯時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditFrom)
                .HasMaxLength(20)
                .HasComment("最後編輯資料來源");
            entity.Property(e => e.Editor).HasComment("最後編輯者ID");
            entity.Property(e => e.GroupSize).HasComment("訂位人數\r\n表示成人訂位人數");
            entity.Property(e => e.MemberId)
                .HasComment("登入會員ID\r\n[FEDSMBR_v3].[Member].[id]\r\n")
                .HasColumnName("memberId");
            entity.Property(e => e.Note)
                .HasMaxLength(500)
                .HasComment("顧客備註");
            entity.Property(e => e.NumberOfKid).HasComment("訂位人數\r\n代表小孩訂位人數");
            entity.Property(e => e.Purpose)
                .HasMaxLength(50)
                .HasComment("用餐目的");
            entity.Property(e => e.Remark)
                .HasMaxLength(200)
                .HasComment("系統備註");
        });

        modelBuilder.Entity<MemberWaitingLog>(entity =>
        {
            entity.ToTable("MemberWaitingLog");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.Json)
                .IsRequired()
                .HasComment("修改紀錄\r\nJson陣列\r\n[0]:為修改前資料,\r\n[1]:為修改後資料");
            entity.Property(e => e.ReserveId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("訂位資訊ID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("Log狀態\r\nCreate=新增,\r\nEdit=修改,\r\nDelete=刪除");

            entity.HasOne(d => d.Reserve).WithMany(p => p.MemberWaitingLogs)
                .HasForeignKey(d => d.ReserveId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MemberWaitingLog");
        });

        modelBuilder.Entity<Restaurant>(entity =>
        {
            entity.ToTable("Restaurant");

            entity.Property(e => e.Id)
                .HasMaxLength(60)
                .HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.EditDate)
                .HasComment("最後編輯時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditFrom)
                .HasMaxLength(20)
                .HasComment("最後編輯資料來源");
            entity.Property(e => e.Editor).HasComment("最後編輯者ID");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("餐聽名稱");
            entity.Property(e => e.Remark)
                .HasMaxLength(50)
                .HasComment("系統備註");
            entity.Property(e => e.Type).HasComment("餐廳類型ID");
        });

        modelBuilder.Entity<RestaurantBranch>(entity =>
        {
            entity.ToTable("RestaurantBranch");

            entity.Property(e => e.Id)
                .HasMaxLength(60)
                .HasColumnName("id");
            entity.Property(e => e.Address)
                .IsRequired()
                .HasMaxLength(200)
                .HasComment("餐廳地址");
            entity.Property(e => e.CompanyId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("餐廳ID  ([Restaurant].[id])");
            entity.Property(e => e.CreateDate)
                .HasComment("資料創建時間")
                .HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .IsRequired()
                .HasMaxLength(20)
                .HasComment("資料創建來源");
            entity.Property(e => e.Creator).HasComment("資料創建者ID");
            entity.Property(e => e.EditDate)
                .HasComment("最後編輯時間")
                .HasColumnType("datetime");
            entity.Property(e => e.EditFrom)
                .HasMaxLength(20)
                .HasComment("最後編輯資料來源");
            entity.Property(e => e.Editor).HasComment("最後編輯者ID");
            entity.Property(e => e.GroupId)
                .IsRequired()
                .HasMaxLength(60)
                .HasComment("所屬分公司ID  ([MallGroup].[id])");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasComment("餐廳分店名稱");
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(30)
                .HasComment("聯絡電話");
            entity.Property(e => e.Remark)
                .HasMaxLength(10)
                .IsFixedLength()
                .HasComment("備註");
            entity.Property(e => e.WebBookingEnable)
                .HasComment("是否開啟網路訂位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RestaurantBranch_BookingEnable");
            entity.Property(e => e.WebWaitingEnable)
                .HasComment("是否開啟預約候位")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_RestaurantBranch_WaitingEnable");

            entity.HasOne(d => d.Company).WithMany(p => p.RestaurantBranches)
                .HasForeignKey(d => d.CompanyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Branch_Company");

            entity.HasOne(d => d.Group).WithMany(p => p.RestaurantBranches)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Branch_Group");
        });

        modelBuilder.Entity<RestaurantImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_RestaurantIMG");

            entity.ToTable("RestaurantImage");

            entity.Property(e => e.CreateDate).HasColumnType("datetime");
            entity.Property(e => e.CreateFrom)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.KeyId)
                .IsRequired()
                .HasMaxLength(60);
            entity.Property(e => e.Src)
                .IsRequired()
                .HasMaxLength(200);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}