// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFRestaurantModels;

public partial class RestaurantImage
{
    public int Id { get; set; }

    public string KeyId { get; set; }

    public string Src { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreateFrom { get; set; }
}