//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FEDSRESTAURANTEntities : DbContext
    {
        public FEDSRESTAURANTEntities()
            : base("name=FEDSRESTAURANTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MallGroup> MallGroups { get; set; }
        public virtual DbSet<MemberReserve> MemberReserves { get; set; }
        public virtual DbSet<MemberReserveLog> MemberReserveLogs { get; set; }
        public virtual DbSet<MemberWaiting> MemberWaitings { get; set; }
        public virtual DbSet<MemberWaitingLog> MemberWaitingLogs { get; set; }
        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public virtual DbSet<RestaurantBranch> RestaurantBranches { get; set; }
        public virtual DbSet<RestaurantImage> RestaurantImages { get; set; }
        public virtual DbSet<RestaurantType> RestaurantTypes { get; set; }
    }
}
