//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberReserve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MemberReserve()
        {
            this.MemberReserveLogs = new HashSet<MemberReserveLog>();
        }
    
        public long id { get; set; }
        public int memberId { get; set; }
        public string CompanyId { get; set; }
        public string BranchId { get; set; }
        public int GroupSize { get; set; }
        public int NumberOfKid { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public byte ContactGender { get; set; }
        public string ContactEmail { get; set; }
        public System.DateTime Datetime { get; set; }
        public string Note { get; set; }
        public string Remark { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateFrom { get; set; }
        public Nullable<int> Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditFrom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberReserveLog> MemberReserveLogs { get; set; }
    }
}
