//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantBranch
    {
        public string id { get; set; }
        public string CompanyId { get; set; }
        public string GroupId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public bool WebBookingEnable { get; set; }
        public bool WebWaitingEnable { get; set; }
        public string Remark { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateFrom { get; set; }
        public Nullable<int> Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditFrom { get; set; }
        public Nullable<bool> IsUse { get; set; }
    
        public virtual MallGroup MallGroup { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
