//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantImage
    {
        public int id { get; set; }
        public string KeyId { get; set; }
        public string Type { get; set; }
        public string Src { get; set; }
        public string Description { get; set; }
        public Nullable<int> Sort { get; set; }
        public int Creator { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateFrom { get; set; }
        public Nullable<int> Editor { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public string EditFrom { get; set; }
    }
}
