// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFMemeberModels;

/// <summary>
/// 會員憑證資料表
/// </summary>
public partial class MemberToken
{
    /// <summary>
    /// 資料編號
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 登入來源(對應ApplicationRole)
    /// </summary>
    public int ApId { get; set; }

    /// <summary>
    /// 會員編號
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// 憑證
    /// </summary>
    public Guid Token { get; set; }

    /// <summary>
    /// 到期時間
    /// </summary>
    public DateTime? ExpireDate { get; set; }

    /// <summary>
    /// 新會員憑證資料編號
    /// </summary>
    public int? NewMemberTokenId { get; set; }

    /// <summary>
    /// 0:下架 1:上架
    /// </summary>
    public int EntityStatus { get; set; }

    public virtual Member Member { get; set; }
}