// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Reservation.Models.EFMemeberModels;

public partial class MemberContext : DbContext
{
    public MemberContext(DbContextOptions<MemberContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberToken> MemberTokens { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Member>(entity =>
        {
            entity.ToTable("Member");

            entity.HasIndex(e => e.Cellphone, "IX_Member_Cellphone").HasFillFactor(80);

            entity.Property(e => e.Id).HasComment("流水號");
            entity.Property(e => e.Account)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("會員識別碼");
            entity.Property(e => e.Address)
                .HasMaxLength(200)
                .HasComment("地址");
            entity.Property(e => e.ApId)
                .HasMaxLength(20)
                .HasComment("註冊網站");
            entity.Property(e => e.AppleId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Apple ID");
            entity.Property(e => e.Area)
                .HasMaxLength(50)
                .HasComment("區域");
            entity.Property(e => e.Birthday)
                .HasComment("生日")
                .HasColumnType("datetime");
            entity.Property(e => e.Cellphone)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("手機");
            entity.Property(e => e.City)
                .HasMaxLength(50)
                .HasComment("縣市");
            entity.Property(e => e.CreateDate)
                .HasComment("建立日期")
                .HasColumnType("datetime");
            entity.Property(e => e.EditDate)
                .HasComment("異動日期")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Email");
            entity.Property(e => e.EventNo)
                .HasMaxLength(20)
                .HasComment("活動代碼");
            entity.Property(e => e.FbId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Facebook ID");
            entity.Property(e => e.GeId)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasComment("Google ID");
            entity.Property(e => e.Gender)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasComment("性別");
            entity.Property(e => e.HgAgreeDate)
                .HasComment("同意日期")
                .HasColumnType("datetime");
            entity.Property(e => e.HgCardNo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("HappyGo卡號");
            entity.Property(e => e.HgValidDate).HasColumnType("datetime");
            entity.Property(e => e.HgpId)
                .HasMaxLength(32)
                .IsUnicode(false)
                .HasComment("Happy go pay id");
            entity.Property(e => e.LastAccessIp)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("IP")
                .HasColumnName("LastAccessIP");
            entity.Property(e => e.LineId).HasComment("LineId");
            entity.Property(e => e.MobileCarrier)
                .HasMaxLength(8)
                .IsUnicode(false)
                .IsFixedLength()
                .HasComment("手機載具");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasComment("姓名");
            entity.Property(e => e.Note).HasComment("備註");
            entity.Property(e => e.NotifyDm)
                .HasComment("Email通知")
                .HasColumnName("NotifyDM");
            entity.Property(e => e.NotifySms)
                .HasComment("簡訊通知")
                .HasColumnName("NotifySMS");
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("密碼");
            entity.Property(e => e.PdpAgreeDate).HasColumnType("datetime");
            entity.Property(e => e.PersonContactId).HasComment("PersonContactId");
            entity.Property(e => e.RealValidDate)
                .HasComment("實名驗證日期")
                .HasColumnType("datetime");
            entity.Property(e => e.Road)
                .HasMaxLength(50)
                .HasComment("路段");
            entity.Property(e => e.RocId)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasComment("身分證字號");
            entity.Property(e => e.Status).HasComment("資料狀態 (0=下架; 1=上架)");
            entity.Property(e => e.TempHgCardNo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasComment("原實體卡號");
            entity.Property(e => e.ZipCode)
                .HasMaxLength(5)
                .IsUnicode(false);
        });

        modelBuilder.Entity<MemberToken>(entity =>
        {
            entity.ToTable("MemberToken", tb => tb.HasComment("會員憑證資料表"));

            entity.HasIndex(e => e.Token, "IX_MemberToken");

            entity.HasIndex(e => e.MemberId, "IX_MemberToken_MemberId").HasFillFactor(80);

            entity.HasIndex(e => e.Token, "NonClusteredIndex-20210930-174025");

            entity.Property(e => e.Id).HasComment("資料編號");
            entity.Property(e => e.ApId).HasComment("登入來源(對應ApplicationRole)");
            entity.Property(e => e.EntityStatus).HasComment("0:下架 1:上架");
            entity.Property(e => e.ExpireDate)
                .HasComment("到期時間")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasComment("會員編號");
            entity.Property(e => e.NewMemberTokenId).HasComment("新會員憑證資料編號");
            entity.Property(e => e.Token).HasComment("憑證");

            entity.HasOne(d => d.Member).WithMany(p => p.MemberTokens)
                .HasForeignKey(d => d.MemberId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_MemberToken_Member");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}