// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reservation.Models.EFMemeberModels;

public partial class Member
{
    /// <summary>
    /// 流水號
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// 手機
    /// </summary>
    public string Cellphone { get; set; }

    /// <summary>
    /// Email
    /// </summary>
    public string Email { get; set; }

    /// <summary>
    /// 會員識別碼
    /// </summary>
    public string Account { get; set; }

    /// <summary>
    /// 密碼
    /// </summary>
    public string Password { get; set; }

    /// <summary>
    /// 姓名
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// 性別
    /// </summary>
    public string Gender { get; set; }

    /// <summary>
    /// 生日
    /// </summary>
    public DateTime? Birthday { get; set; }

    /// <summary>
    /// 身分證字號
    /// </summary>
    public string RocId { get; set; }

    public string ZipCode { get; set; }

    /// <summary>
    /// 縣市
    /// </summary>
    public string City { get; set; }

    /// <summary>
    /// 區域
    /// </summary>
    public string Area { get; set; }

    /// <summary>
    /// 路段
    /// </summary>
    public string Road { get; set; }

    /// <summary>
    /// 地址
    /// </summary>
    public string Address { get; set; }

    /// <summary>
    /// 手機載具
    /// </summary>
    public string MobileCarrier { get; set; }

    /// <summary>
    /// 簡訊通知
    /// </summary>
    public int NotifySms { get; set; }

    /// <summary>
    /// Email通知
    /// </summary>
    public int NotifyDm { get; set; }

    /// <summary>
    /// Facebook ID
    /// </summary>
    public string FbId { get; set; }

    /// <summary>
    /// Google ID
    /// </summary>
    public string GeId { get; set; }

    /// <summary>
    /// LineId
    /// </summary>
    public string LineId { get; set; }

    /// <summary>
    /// Apple ID
    /// </summary>
    public string AppleId { get; set; }

    /// <summary>
    /// Happy go pay id
    /// </summary>
    public string HgpId { get; set; }

    /// <summary>
    /// 註冊網站
    /// </summary>
    public string ApId { get; set; }

    /// <summary>
    /// 原實體卡號
    /// </summary>
    public string TempHgCardNo { get; set; }

    /// <summary>
    /// HappyGo卡號
    /// </summary>
    public string HgCardNo { get; set; }

    /// <summary>
    /// 同意日期
    /// </summary>
    public DateTime? HgAgreeDate { get; set; }

    public DateTime? HgValidDate { get; set; }

    /// <summary>
    /// 實名驗證日期
    /// </summary>
    public DateTime? RealValidDate { get; set; }

    public DateTime? PdpAgreeDate { get; set; }

    /// <summary>
    /// PersonContactId
    /// </summary>
    public string PersonContactId { get; set; }

    /// <summary>
    /// 活動代碼
    /// </summary>
    public string EventNo { get; set; }

    /// <summary>
    /// 建立日期
    /// </summary>
    public DateTime CreateDate { get; set; }

    /// <summary>
    /// 異動日期
    /// </summary>
    public DateTime? EditDate { get; set; }

    /// <summary>
    /// IP
    /// </summary>
    public string LastAccessIp { get; set; }

    /// <summary>
    /// 資料狀態 (0=下架; 1=上架)
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// 備註
    /// </summary>
    public string Note { get; set; }

    public virtual ICollection<MemberToken> MemberTokens { get; set; } = new List<MemberToken>();
}